name: 'facebook_ads'
version: '0.8.0'
config-version: 2

require-dbt-version: [">=1.3.0", "<2.0.0"]

model-paths: ["models"]   # paths with source code to compile
analysis-paths: ["analyses"] # path with analysis files which are compiled, but not run
target-path: "target"      # path for compiled code
clean-targets: ["target"]  # directories removed by the clean task
test-paths: ["test"]       # where to store test results
seed-paths: ["seeds"]       # load CSVs from this directory with `dbt seed`

vars:

  etl:                                   #stitch or fivetran
  ads_table:                             #table
  ad_creatives_table:                    #table
  adsets_table:                          #table
  campaigns_table:                       #table
  ads_insights_table:                    #table
  ad_creatives__child_links_table:       #table -- disable if on snowflake

  url_tag_table:                         #only for fivetran

models:
  facebook_ads:
